/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Unused;

/**
 *
 * @author LATITUDE 5480
 */
public class KnockoutBracket0 extends javax.swing.JFrame {

    /**
     * Creates new form KnockoutBracket
     */
    public KnockoutBracket0() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        knockoutTournament_panel1 = new javax.swing.JPanel();
        roundOf32_txt1 = new javax.swing.JLabel();
        roundOf32_panel1 = new javax.swing.JPanel();
        R1participant32 = new javax.swing.JLabel();
        R1participant33 = new javax.swing.JLabel();
        R1participant34 = new javax.swing.JLabel();
        R1participant35 = new javax.swing.JLabel();
        R1participant36 = new javax.swing.JLabel();
        R1participant37 = new javax.swing.JLabel();
        R1participant38 = new javax.swing.JLabel();
        R1participant39 = new javax.swing.JLabel();
        R1participant40 = new javax.swing.JLabel();
        R1participant41 = new javax.swing.JLabel();
        R1participant42 = new javax.swing.JLabel();
        R1participant43 = new javax.swing.JLabel();
        R1participant44 = new javax.swing.JLabel();
        R1participant45 = new javax.swing.JLabel();
        R1participant46 = new javax.swing.JLabel();
        R1participant47 = new javax.swing.JLabel();
        R1participant48 = new javax.swing.JLabel();
        R1participant49 = new javax.swing.JLabel();
        R1participant50 = new javax.swing.JLabel();
        R1participant51 = new javax.swing.JLabel();
        R1participant52 = new javax.swing.JLabel();
        R1participant53 = new javax.swing.JLabel();
        R1participant54 = new javax.swing.JLabel();
        R1participant55 = new javax.swing.JLabel();
        R1participant56 = new javax.swing.JLabel();
        R1participant57 = new javax.swing.JLabel();
        R1participant58 = new javax.swing.JLabel();
        R1participant59 = new javax.swing.JLabel();
        R1participant60 = new javax.swing.JLabel();
        R1participant61 = new javax.swing.JLabel();
        R1participant62 = new javax.swing.JLabel();
        R1participant63 = new javax.swing.JLabel();
        R1points32 = new javax.swing.JLabel();
        R1points33 = new javax.swing.JLabel();
        R1points34 = new javax.swing.JLabel();
        R1points35 = new javax.swing.JLabel();
        R1points36 = new javax.swing.JLabel();
        R1points37 = new javax.swing.JLabel();
        R1points38 = new javax.swing.JLabel();
        R1points39 = new javax.swing.JLabel();
        R1points40 = new javax.swing.JLabel();
        R1points41 = new javax.swing.JLabel();
        R1points42 = new javax.swing.JLabel();
        R1points43 = new javax.swing.JLabel();
        R1points44 = new javax.swing.JLabel();
        R1points45 = new javax.swing.JLabel();
        R1points46 = new javax.swing.JLabel();
        R1points47 = new javax.swing.JLabel();
        R1points48 = new javax.swing.JLabel();
        R1points49 = new javax.swing.JLabel();
        R1points50 = new javax.swing.JLabel();
        R1points51 = new javax.swing.JLabel();
        R1points52 = new javax.swing.JLabel();
        R1points53 = new javax.swing.JLabel();
        R1points54 = new javax.swing.JLabel();
        R1points55 = new javax.swing.JLabel();
        R1points56 = new javax.swing.JLabel();
        R1points57 = new javax.swing.JLabel();
        R1points58 = new javax.swing.JLabel();
        R1points59 = new javax.swing.JLabel();
        R1points60 = new javax.swing.JLabel();
        R1points61 = new javax.swing.JLabel();
        R1points62 = new javax.swing.JLabel();
        R1points63 = new javax.swing.JLabel();
        roundOf16_panel1 = new javax.swing.JPanel();
        R2participant16 = new javax.swing.JLabel();
        R2participant17 = new javax.swing.JLabel();
        R2participant18 = new javax.swing.JLabel();
        R2participant19 = new javax.swing.JLabel();
        R2participant20 = new javax.swing.JLabel();
        R2participant21 = new javax.swing.JLabel();
        R2participant22 = new javax.swing.JLabel();
        R2participant23 = new javax.swing.JLabel();
        R2participant24 = new javax.swing.JLabel();
        R2participant25 = new javax.swing.JLabel();
        R2participant26 = new javax.swing.JLabel();
        R2participant27 = new javax.swing.JLabel();
        R2participant28 = new javax.swing.JLabel();
        R2participant29 = new javax.swing.JLabel();
        R2participant30 = new javax.swing.JLabel();
        R2participant31 = new javax.swing.JLabel();
        R2points16 = new javax.swing.JLabel();
        R2points17 = new javax.swing.JLabel();
        R2points18 = new javax.swing.JLabel();
        R2points19 = new javax.swing.JLabel();
        R2points20 = new javax.swing.JLabel();
        R2points21 = new javax.swing.JLabel();
        R2points22 = new javax.swing.JLabel();
        R2points23 = new javax.swing.JLabel();
        R2points24 = new javax.swing.JLabel();
        R2points25 = new javax.swing.JLabel();
        R2points26 = new javax.swing.JLabel();
        R2points27 = new javax.swing.JLabel();
        R2points28 = new javax.swing.JLabel();
        R2points29 = new javax.swing.JLabel();
        R2points30 = new javax.swing.JLabel();
        R2points31 = new javax.swing.JLabel();
        quarterFinals_panel1 = new javax.swing.JPanel();
        R3participant8 = new javax.swing.JLabel();
        R3points8 = new javax.swing.JLabel();
        R3participant9 = new javax.swing.JLabel();
        R3points9 = new javax.swing.JLabel();
        R3participant10 = new javax.swing.JLabel();
        R3points10 = new javax.swing.JLabel();
        R3participant11 = new javax.swing.JLabel();
        R3points11 = new javax.swing.JLabel();
        R3participant12 = new javax.swing.JLabel();
        R3points12 = new javax.swing.JLabel();
        R3participant13 = new javax.swing.JLabel();
        R3points13 = new javax.swing.JLabel();
        R3participant14 = new javax.swing.JLabel();
        R3points14 = new javax.swing.JLabel();
        R3participant15 = new javax.swing.JLabel();
        R3points15 = new javax.swing.JLabel();
        roundOd16_txt1 = new javax.swing.JLabel();
        quaterFinals_txt1 = new javax.swing.JLabel();
        semiFinals_panel1 = new javax.swing.JPanel();
        R4participant4 = new javax.swing.JLabel();
        R4points4 = new javax.swing.JLabel();
        R4participant5 = new javax.swing.JLabel();
        R4points5 = new javax.swing.JLabel();
        R4participant6 = new javax.swing.JLabel();
        R4points6 = new javax.swing.JLabel();
        R4participant7 = new javax.swing.JLabel();
        R4points7 = new javax.swing.JLabel();
        finals_panel1 = new javax.swing.JPanel();
        R5participant2 = new javax.swing.JLabel();
        R5points2 = new javax.swing.JLabel();
        R5participant3 = new javax.swing.JLabel();
        R5points3 = new javax.swing.JLabel();
        semiFinals_txt1 = new javax.swing.JLabel();
        finals_txt1 = new javax.swing.JLabel();
        winners_panel1 = new javax.swing.JPanel();
        winner1 = new javax.swing.JLabel();
        winner_txt1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        knockoutTournament_panel1.setBackground(new java.awt.Color(51, 0, 0));

        roundOf32_txt1.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        roundOf32_txt1.setForeground(new java.awt.Color(255, 102, 102));
        roundOf32_txt1.setText("Round of 32");

        roundOf32_panel1.setBackground(new java.awt.Color(51, 0, 0));
        roundOf32_panel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        roundOf32_panel1.setForeground(new java.awt.Color(51, 0, 0));

        R1participant32.setBackground(new java.awt.Color(255, 255, 255));
        R1participant32.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R1participant32.setForeground(new java.awt.Color(255, 255, 255));
        R1participant32.setText(" ");

        R1participant33.setBackground(new java.awt.Color(255, 255, 255));
        R1participant33.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R1participant33.setForeground(new java.awt.Color(255, 255, 255));
        R1participant33.setText(" ");

        R1participant34.setBackground(new java.awt.Color(255, 255, 255));
        R1participant34.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R1participant34.setForeground(new java.awt.Color(255, 255, 255));
        R1participant34.setText(" ");

        R1participant35.setBackground(new java.awt.Color(255, 255, 255));
        R1participant35.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R1participant35.setForeground(new java.awt.Color(255, 255, 255));
        R1participant35.setText(" ");

        R1participant36.setBackground(new java.awt.Color(255, 255, 255));
        R1participant36.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R1participant36.setForeground(new java.awt.Color(255, 255, 255));
        R1participant36.setText(" ");

        R1participant37.setBackground(new java.awt.Color(255, 255, 255));
        R1participant37.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R1participant37.setForeground(new java.awt.Color(255, 255, 255));
        R1participant37.setText(" ");

        R1participant38.setBackground(new java.awt.Color(255, 255, 255));
        R1participant38.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R1participant38.setForeground(new java.awt.Color(255, 255, 255));
        R1participant38.setText(" ");

        R1participant39.setBackground(new java.awt.Color(255, 255, 255));
        R1participant39.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R1participant39.setForeground(new java.awt.Color(255, 255, 255));
        R1participant39.setText(" ");

        R1participant40.setBackground(new java.awt.Color(255, 255, 255));
        R1participant40.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R1participant40.setForeground(new java.awt.Color(255, 255, 255));
        R1participant40.setText(" ");

        R1participant41.setBackground(new java.awt.Color(255, 255, 255));
        R1participant41.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R1participant41.setForeground(new java.awt.Color(255, 255, 255));
        R1participant41.setText(" ");

        R1participant42.setBackground(new java.awt.Color(255, 255, 255));
        R1participant42.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R1participant42.setForeground(new java.awt.Color(255, 255, 255));
        R1participant42.setText(" ");

        R1participant43.setBackground(new java.awt.Color(255, 255, 255));
        R1participant43.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R1participant43.setForeground(new java.awt.Color(255, 255, 255));
        R1participant43.setText(" ");

        R1participant44.setBackground(new java.awt.Color(255, 255, 255));
        R1participant44.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R1participant44.setForeground(new java.awt.Color(255, 255, 255));
        R1participant44.setText(" ");

        R1participant45.setBackground(new java.awt.Color(255, 255, 255));
        R1participant45.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R1participant45.setForeground(new java.awt.Color(255, 255, 255));
        R1participant45.setText(" ");

        R1participant46.setBackground(new java.awt.Color(255, 255, 255));
        R1participant46.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R1participant46.setForeground(new java.awt.Color(255, 255, 255));
        R1participant46.setText(" ");

        R1participant47.setBackground(new java.awt.Color(255, 255, 255));
        R1participant47.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R1participant47.setForeground(new java.awt.Color(255, 255, 255));
        R1participant47.setText(" ");

        R1participant48.setBackground(new java.awt.Color(255, 255, 255));
        R1participant48.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R1participant48.setForeground(new java.awt.Color(255, 255, 255));
        R1participant48.setText(" ");

        R1participant49.setBackground(new java.awt.Color(255, 255, 255));
        R1participant49.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R1participant49.setForeground(new java.awt.Color(255, 255, 255));
        R1participant49.setText(" ");

        R1participant50.setBackground(new java.awt.Color(255, 255, 255));
        R1participant50.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R1participant50.setForeground(new java.awt.Color(255, 255, 255));
        R1participant50.setText(" ");

        R1participant51.setBackground(new java.awt.Color(255, 255, 255));
        R1participant51.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R1participant51.setForeground(new java.awt.Color(255, 255, 255));
        R1participant51.setText(" ");

        R1participant52.setBackground(new java.awt.Color(255, 255, 255));
        R1participant52.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R1participant52.setForeground(new java.awt.Color(255, 255, 255));
        R1participant52.setText(" ");

        R1participant53.setBackground(new java.awt.Color(255, 255, 255));
        R1participant53.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R1participant53.setForeground(new java.awt.Color(255, 255, 255));
        R1participant53.setText(" ");

        R1participant54.setBackground(new java.awt.Color(255, 255, 255));
        R1participant54.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R1participant54.setForeground(new java.awt.Color(255, 255, 255));
        R1participant54.setText(" ");

        R1participant55.setBackground(new java.awt.Color(255, 255, 255));
        R1participant55.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R1participant55.setForeground(new java.awt.Color(255, 255, 255));
        R1participant55.setText(" ");

        R1participant56.setBackground(new java.awt.Color(255, 255, 255));
        R1participant56.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R1participant56.setForeground(new java.awt.Color(255, 255, 255));
        R1participant56.setText(" ");

        R1participant57.setBackground(new java.awt.Color(255, 255, 255));
        R1participant57.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R1participant57.setForeground(new java.awt.Color(255, 255, 255));
        R1participant57.setText(" ");

        R1participant58.setBackground(new java.awt.Color(255, 255, 255));
        R1participant58.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R1participant58.setForeground(new java.awt.Color(255, 255, 255));
        R1participant58.setText(" ");

        R1participant59.setBackground(new java.awt.Color(255, 255, 255));
        R1participant59.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R1participant59.setForeground(new java.awt.Color(255, 255, 255));
        R1participant59.setText(" ");

        R1participant60.setBackground(new java.awt.Color(255, 255, 255));
        R1participant60.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R1participant60.setForeground(new java.awt.Color(255, 255, 255));
        R1participant60.setText(" ");

        R1participant61.setBackground(new java.awt.Color(255, 255, 255));
        R1participant61.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R1participant61.setForeground(new java.awt.Color(255, 255, 255));
        R1participant61.setText(" ");

        R1participant62.setBackground(new java.awt.Color(255, 255, 255));
        R1participant62.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R1participant62.setForeground(new java.awt.Color(255, 255, 255));
        R1participant62.setText(" ");

        R1participant63.setBackground(new java.awt.Color(255, 255, 255));
        R1participant63.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R1participant63.setForeground(new java.awt.Color(255, 255, 255));
        R1participant63.setText(" ");

        R1points32.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R1points32.setText(" ");

        R1points33.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R1points33.setText(" ");

        R1points34.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R1points34.setText(" ");

        R1points35.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R1points35.setText(" ");

        R1points36.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R1points36.setText(" ");

        R1points37.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R1points37.setText(" ");

        R1points38.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R1points38.setText(" ");

        R1points39.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R1points39.setText(" ");

        R1points40.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R1points40.setText(" ");

        R1points41.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R1points41.setText(" ");

        R1points42.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R1points42.setText(" ");

        R1points43.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R1points43.setText(" ");

        R1points44.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R1points44.setText(" ");

        R1points45.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R1points45.setText(" ");

        R1points46.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R1points46.setText(" ");

        R1points47.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R1points47.setText(" ");

        R1points48.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R1points48.setText(" ");

        R1points49.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R1points49.setText(" ");

        R1points50.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R1points50.setText(" ");

        R1points51.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R1points51.setText(" ");

        R1points52.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R1points52.setText(" ");

        R1points53.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R1points53.setText(" ");

        R1points54.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R1points54.setText(" ");

        R1points55.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R1points55.setText(" ");

        R1points56.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R1points56.setText(" ");

        R1points57.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R1points57.setText(" ");

        R1points58.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R1points58.setText(" ");

        R1points59.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R1points59.setText(" ");

        R1points60.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R1points60.setText(" ");

        R1points61.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R1points61.setText(" ");

        R1points62.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R1points62.setText(" ");

        R1points63.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R1points63.setText(" ");

        javax.swing.GroupLayout roundOf32_panel1Layout = new javax.swing.GroupLayout(roundOf32_panel1);
        roundOf32_panel1.setLayout(roundOf32_panel1Layout);
        roundOf32_panel1Layout.setHorizontalGroup(
            roundOf32_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundOf32_panel1Layout.createSequentialGroup()
                .addComponent(R1participant34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R1points34, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(roundOf32_panel1Layout.createSequentialGroup()
                .addComponent(R1participant35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R1points35, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(roundOf32_panel1Layout.createSequentialGroup()
                .addComponent(R1participant36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R1points36, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(roundOf32_panel1Layout.createSequentialGroup()
                .addComponent(R1participant37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R1points37, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(roundOf32_panel1Layout.createSequentialGroup()
                .addComponent(R1participant38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R1points38, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(roundOf32_panel1Layout.createSequentialGroup()
                .addComponent(R1participant39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R1points39, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(roundOf32_panel1Layout.createSequentialGroup()
                .addComponent(R1participant40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R1points40, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(roundOf32_panel1Layout.createSequentialGroup()
                .addComponent(R1participant41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R1points41, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(roundOf32_panel1Layout.createSequentialGroup()
                .addComponent(R1participant42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R1points42, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(roundOf32_panel1Layout.createSequentialGroup()
                .addComponent(R1participant43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R1points43, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(roundOf32_panel1Layout.createSequentialGroup()
                .addComponent(R1participant44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R1points44, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(roundOf32_panel1Layout.createSequentialGroup()
                .addComponent(R1participant46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R1points46, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(roundOf32_panel1Layout.createSequentialGroup()
                .addComponent(R1participant47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R1points47, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundOf32_panel1Layout.createSequentialGroup()
                .addComponent(R1participant48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R1points48, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundOf32_panel1Layout.createSequentialGroup()
                .addComponent(R1participant50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R1points50, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundOf32_panel1Layout.createSequentialGroup()
                .addComponent(R1participant51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R1points51, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundOf32_panel1Layout.createSequentialGroup()
                .addComponent(R1participant52, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R1points52, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundOf32_panel1Layout.createSequentialGroup()
                .addComponent(R1participant53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R1points53, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundOf32_panel1Layout.createSequentialGroup()
                .addComponent(R1participant54, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R1points54, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundOf32_panel1Layout.createSequentialGroup()
                .addComponent(R1participant55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R1points55, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundOf32_panel1Layout.createSequentialGroup()
                .addComponent(R1participant56, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R1points56, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundOf32_panel1Layout.createSequentialGroup()
                .addComponent(R1participant57, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R1points57, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundOf32_panel1Layout.createSequentialGroup()
                .addComponent(R1participant58, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R1points58, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundOf32_panel1Layout.createSequentialGroup()
                .addComponent(R1participant59, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R1points59, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundOf32_panel1Layout.createSequentialGroup()
                .addComponent(R1participant60, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R1points60, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundOf32_panel1Layout.createSequentialGroup()
                .addComponent(R1participant61, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R1points61, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(roundOf32_panel1Layout.createSequentialGroup()
                .addComponent(R1participant49, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R1points49, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(roundOf32_panel1Layout.createSequentialGroup()
                .addComponent(R1participant45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R1points45, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(roundOf32_panel1Layout.createSequentialGroup()
                .addComponent(R1participant63, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(R1points63, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(roundOf32_panel1Layout.createSequentialGroup()
                .addComponent(R1participant62, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(R1points62, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundOf32_panel1Layout.createSequentialGroup()
                .addGroup(roundOf32_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(R1participant32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(R1participant33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundOf32_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(R1points33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R1points32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        roundOf32_panel1Layout.setVerticalGroup(
            roundOf32_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundOf32_panel1Layout.createSequentialGroup()
                .addGroup(roundOf32_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R1participant32)
                    .addComponent(R1points32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundOf32_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R1participant33)
                    .addComponent(R1points33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundOf32_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R1participant34)
                    .addComponent(R1points34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundOf32_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R1participant35)
                    .addComponent(R1points35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundOf32_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R1participant36)
                    .addComponent(R1points36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundOf32_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R1participant37)
                    .addComponent(R1points37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundOf32_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R1participant38)
                    .addComponent(R1points38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundOf32_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R1participant39)
                    .addComponent(R1points39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundOf32_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R1participant40)
                    .addComponent(R1points40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundOf32_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R1participant41)
                    .addComponent(R1points41))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundOf32_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R1participant42)
                    .addComponent(R1points42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundOf32_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R1participant43, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R1points43))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundOf32_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R1participant44)
                    .addComponent(R1points44))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundOf32_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R1participant45)
                    .addComponent(R1points45))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundOf32_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R1participant46)
                    .addComponent(R1points46))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundOf32_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R1participant47)
                    .addComponent(R1points47))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundOf32_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R1participant48)
                    .addComponent(R1points48))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundOf32_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R1participant49)
                    .addComponent(R1points49))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundOf32_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R1participant50)
                    .addComponent(R1points50))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundOf32_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R1participant51)
                    .addComponent(R1points51))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundOf32_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R1participant52)
                    .addComponent(R1points52))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundOf32_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R1participant53)
                    .addComponent(R1points53))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundOf32_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R1participant54)
                    .addComponent(R1points54))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundOf32_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R1participant55)
                    .addComponent(R1points55))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundOf32_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R1participant56)
                    .addComponent(R1points56))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundOf32_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R1participant57)
                    .addComponent(R1points57))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundOf32_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R1participant58)
                    .addComponent(R1points58))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundOf32_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R1participant59, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R1points59))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundOf32_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R1participant60)
                    .addComponent(R1points60))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundOf32_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R1participant61)
                    .addComponent(R1points61))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundOf32_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R1participant62, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R1points62))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(roundOf32_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R1participant63, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R1points63)))
        );

        roundOf16_panel1.setBackground(new java.awt.Color(51, 0, 0));
        roundOf16_panel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        R2participant16.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R2participant16.setText(" ");

        R2participant17.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R2participant17.setText(" ");

        R2participant18.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R2participant18.setText(" ");

        R2participant19.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R2participant19.setText(" ");

        R2participant20.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R2participant20.setText(" ");

        R2participant21.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R2participant21.setText(" ");

        R2participant22.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R2participant22.setText(" ");

        R2participant23.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R2participant23.setText(" ");

        R2participant24.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R2participant24.setText(" ");

        R2participant25.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R2participant25.setText(" ");

        R2participant26.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R2participant26.setText(" ");

        R2participant27.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R2participant27.setText(" ");

        R2participant28.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R2participant28.setText(" ");

        R2participant29.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R2participant29.setText(" ");

        R2participant30.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R2participant30.setText(" ");

        R2participant31.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R2participant31.setText(" ");

        R2points16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R2points16.setText(" ");

        R2points17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R2points17.setText(" ");
        R2points17.setToolTipText("");

        R2points18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R2points18.setText(" ");
        R2points18.setToolTipText("");

        R2points19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R2points19.setText(" ");
        R2points19.setToolTipText("");

        R2points20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R2points20.setText(" ");
        R2points20.setToolTipText("");

        R2points21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R2points21.setText(" ");
        R2points21.setToolTipText("");

        R2points22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R2points22.setText(" ");
        R2points22.setToolTipText("");

        R2points23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R2points23.setText(" ");
        R2points23.setToolTipText("");

        R2points24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R2points24.setText(" ");
        R2points24.setToolTipText("");

        R2points25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R2points25.setText(" ");
        R2points25.setToolTipText("");

        R2points26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R2points26.setText(" ");
        R2points26.setToolTipText("");

        R2points27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R2points27.setText(" ");
        R2points27.setToolTipText("");

        R2points28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R2points28.setText(" ");
        R2points28.setToolTipText("");

        R2points29.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R2points29.setText(" ");
        R2points29.setToolTipText("");

        R2points30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R2points30.setText(" ");
        R2points30.setToolTipText("");

        R2points31.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R2points31.setText(" ");
        R2points31.setToolTipText("");

        javax.swing.GroupLayout roundOf16_panel1Layout = new javax.swing.GroupLayout(roundOf16_panel1);
        roundOf16_panel1.setLayout(roundOf16_panel1Layout);
        roundOf16_panel1Layout.setHorizontalGroup(
            roundOf16_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundOf16_panel1Layout.createSequentialGroup()
                .addComponent(R2participant16, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R2points16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(roundOf16_panel1Layout.createSequentialGroup()
                .addComponent(R2participant17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R2points17, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(roundOf16_panel1Layout.createSequentialGroup()
                .addComponent(R2participant18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R2points18, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(roundOf16_panel1Layout.createSequentialGroup()
                .addComponent(R2participant19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R2points19, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(roundOf16_panel1Layout.createSequentialGroup()
                .addComponent(R2participant20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R2points20, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(roundOf16_panel1Layout.createSequentialGroup()
                .addComponent(R2participant21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R2points21, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(roundOf16_panel1Layout.createSequentialGroup()
                .addComponent(R2participant22, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R2points22, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(roundOf16_panel1Layout.createSequentialGroup()
                .addComponent(R2participant23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R2points23, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(roundOf16_panel1Layout.createSequentialGroup()
                .addComponent(R2participant24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R2points24, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(roundOf16_panel1Layout.createSequentialGroup()
                .addComponent(R2participant25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R2points31, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(roundOf16_panel1Layout.createSequentialGroup()
                .addComponent(R2participant26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R2points30, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(roundOf16_panel1Layout.createSequentialGroup()
                .addComponent(R2participant27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R2points29, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(roundOf16_panel1Layout.createSequentialGroup()
                .addComponent(R2participant28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R2points28, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(roundOf16_panel1Layout.createSequentialGroup()
                .addComponent(R2participant29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R2points27, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(roundOf16_panel1Layout.createSequentialGroup()
                .addComponent(R2participant30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R2points26, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(roundOf16_panel1Layout.createSequentialGroup()
                .addComponent(R2participant31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R2points25, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        roundOf16_panel1Layout.setVerticalGroup(
            roundOf16_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundOf16_panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundOf16_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R2participant16)
                    .addComponent(R2points16))
                .addGap(25, 25, 25)
                .addGroup(roundOf16_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R2participant17)
                    .addComponent(R2points17))
                .addGap(28, 28, 28)
                .addGroup(roundOf16_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R2participant18)
                    .addComponent(R2points18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(roundOf16_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R2participant19)
                    .addComponent(R2points19))
                .addGap(27, 27, 27)
                .addGroup(roundOf16_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R2participant20)
                    .addComponent(R2points20))
                .addGap(27, 27, 27)
                .addGroup(roundOf16_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R2participant21, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R2points21))
                .addGap(27, 27, 27)
                .addGroup(roundOf16_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R2participant22)
                    .addComponent(R2points22))
                .addGap(26, 26, 26)
                .addGroup(roundOf16_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R2participant23)
                    .addComponent(R2points23))
                .addGap(29, 29, 29)
                .addGroup(roundOf16_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R2participant24)
                    .addComponent(R2points24))
                .addGap(27, 27, 27)
                .addGroup(roundOf16_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R2participant31)
                    .addComponent(R2points25))
                .addGap(26, 26, 26)
                .addGroup(roundOf16_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R2participant30)
                    .addComponent(R2points26))
                .addGap(25, 25, 25)
                .addGroup(roundOf16_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R2participant29)
                    .addComponent(R2points27))
                .addGap(27, 27, 27)
                .addGroup(roundOf16_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R2participant28)
                    .addComponent(R2points28))
                .addGap(28, 28, 28)
                .addGroup(roundOf16_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R2participant27)
                    .addComponent(R2points29))
                .addGap(28, 28, 28)
                .addGroup(roundOf16_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R2participant26)
                    .addComponent(R2points30))
                .addGap(25, 25, 25)
                .addGroup(roundOf16_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R2participant25)
                    .addComponent(R2points31))
                .addContainerGap())
        );

        quarterFinals_panel1.setBackground(new java.awt.Color(51, 0, 0));
        quarterFinals_panel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        R3participant8.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R3participant8.setForeground(new java.awt.Color(153, 153, 153));

        R3points8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R3points8.setText(" ");

        R3participant9.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R3participant9.setForeground(new java.awt.Color(255, 255, 255));
        R3participant9.setText(" ");

        R3points9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R3points9.setText(" ");

        R3participant10.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R3participant10.setForeground(new java.awt.Color(255, 255, 255));
        R3participant10.setText(" ");

        R3points10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R3points10.setText(" ");

        R3participant11.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R3participant11.setForeground(new java.awt.Color(255, 255, 255));
        R3participant11.setText(" ");

        R3points11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R3points11.setText(" ");

        R3participant12.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R3participant12.setForeground(new java.awt.Color(255, 255, 255));
        R3participant12.setText(" ");

        R3points12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R3points12.setText(" ");

        R3participant13.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R3participant13.setForeground(new java.awt.Color(255, 255, 255));
        R3participant13.setText(" ");

        R3points13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R3points13.setText(" ");

        R3participant14.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R3participant14.setForeground(new java.awt.Color(255, 255, 255));
        R3participant14.setText(" ");

        R3points14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R3points14.setText(" ");

        R3participant15.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R3participant15.setForeground(new java.awt.Color(255, 255, 255));
        R3participant15.setText(" ");

        R3points15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R3points15.setText(" ");

        javax.swing.GroupLayout quarterFinals_panel1Layout = new javax.swing.GroupLayout(quarterFinals_panel1);
        quarterFinals_panel1.setLayout(quarterFinals_panel1Layout);
        quarterFinals_panel1Layout.setHorizontalGroup(
            quarterFinals_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quarterFinals_panel1Layout.createSequentialGroup()
                .addComponent(R3participant8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(R3points8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(quarterFinals_panel1Layout.createSequentialGroup()
                .addComponent(R3participant9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R3points9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(quarterFinals_panel1Layout.createSequentialGroup()
                .addComponent(R3participant10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R3points10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(quarterFinals_panel1Layout.createSequentialGroup()
                .addComponent(R3participant11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R3points11, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quarterFinals_panel1Layout.createSequentialGroup()
                .addGroup(quarterFinals_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(R3participant13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(R3participant12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(quarterFinals_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(R3points12, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R3points13, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(quarterFinals_panel1Layout.createSequentialGroup()
                .addComponent(R3participant14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R3points14, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(quarterFinals_panel1Layout.createSequentialGroup()
                .addComponent(R3participant15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R3points15, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        quarterFinals_panel1Layout.setVerticalGroup(
            quarterFinals_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quarterFinals_panel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(quarterFinals_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R3participant8)
                    .addComponent(R3points8))
                .addGap(69, 69, 69)
                .addGroup(quarterFinals_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R3participant9)
                    .addComponent(R3points9))
                .addGap(69, 69, 69)
                .addGroup(quarterFinals_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R3participant10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R3points10))
                .addGap(69, 69, 69)
                .addGroup(quarterFinals_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R3participant11)
                    .addComponent(R3points11))
                .addGap(69, 69, 69)
                .addGroup(quarterFinals_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R3participant12)
                    .addComponent(R3points12))
                .addGap(69, 69, 69)
                .addGroup(quarterFinals_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R3participant13)
                    .addComponent(R3points13))
                .addGap(69, 69, 69)
                .addGroup(quarterFinals_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R3participant14)
                    .addComponent(R3points14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(quarterFinals_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R3participant15)
                    .addComponent(R3points15))
                .addGap(32, 32, 32))
        );

        roundOd16_txt1.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        roundOd16_txt1.setForeground(new java.awt.Color(255, 102, 102));
        roundOd16_txt1.setText("Round of 16");

        quaterFinals_txt1.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        quaterFinals_txt1.setForeground(new java.awt.Color(255, 102, 102));
        quaterFinals_txt1.setText("Quarter-Finals");

        semiFinals_panel1.setBackground(new java.awt.Color(51, 0, 0));
        semiFinals_panel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        semiFinals_panel1.setForeground(new java.awt.Color(51, 0, 0));

        R4participant4.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R4participant4.setText(" ");

        R4points4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R4points4.setText(" ");

        R4participant5.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R4participant5.setText(" ");

        R4points5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R4points5.setText(" ");

        R4participant6.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R4participant6.setText(" ");

        R4points6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R4points6.setText(" ");

        R4participant7.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        R4participant7.setText(" ");

        R4points7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R4points7.setText(" ");

        javax.swing.GroupLayout semiFinals_panel1Layout = new javax.swing.GroupLayout(semiFinals_panel1);
        semiFinals_panel1.setLayout(semiFinals_panel1Layout);
        semiFinals_panel1Layout.setHorizontalGroup(
            semiFinals_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(semiFinals_panel1Layout.createSequentialGroup()
                .addComponent(R4participant4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R4points4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(semiFinals_panel1Layout.createSequentialGroup()
                .addComponent(R4participant5, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R4points5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(semiFinals_panel1Layout.createSequentialGroup()
                .addComponent(R4participant6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R4points6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(semiFinals_panel1Layout.createSequentialGroup()
                .addComponent(R4participant7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R4points7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        semiFinals_panel1Layout.setVerticalGroup(
            semiFinals_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(semiFinals_panel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(semiFinals_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R4participant4)
                    .addComponent(R4points4))
                .addGap(153, 153, 153)
                .addGroup(semiFinals_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R4participant5)
                    .addComponent(R4points5))
                .addGap(154, 154, 154)
                .addGroup(semiFinals_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R4participant6)
                    .addComponent(R4points6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(semiFinals_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R4participant7)
                    .addComponent(R4points7))
                .addGap(77, 77, 77))
        );

        finals_panel1.setBackground(new java.awt.Color(51, 0, 0));
        finals_panel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        R5participant2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        R5participant2.setForeground(new java.awt.Color(255, 255, 255));
        R5participant2.setText(" ");

        R5points2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R5points2.setText(" ");

        R5participant3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        R5participant3.setForeground(new java.awt.Color(255, 255, 255));
        R5participant3.setText(" ");

        R5points3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R5points3.setText(" ");

        javax.swing.GroupLayout finals_panel1Layout = new javax.swing.GroupLayout(finals_panel1);
        finals_panel1.setLayout(finals_panel1Layout);
        finals_panel1Layout.setHorizontalGroup(
            finals_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(finals_panel1Layout.createSequentialGroup()
                .addComponent(R5participant2, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R5points2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(finals_panel1Layout.createSequentialGroup()
                .addComponent(R5participant3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R5points3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        finals_panel1Layout.setVerticalGroup(
            finals_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(finals_panel1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(finals_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R5participant2)
                    .addComponent(R5points2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 324, Short.MAX_VALUE)
                .addGroup(finals_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R5participant3)
                    .addComponent(R5points3))
                .addGap(163, 163, 163))
        );

        semiFinals_txt1.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        semiFinals_txt1.setForeground(new java.awt.Color(255, 102, 102));
        semiFinals_txt1.setText("Semi-Finals");

        finals_txt1.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        finals_txt1.setForeground(new java.awt.Color(255, 51, 51));
        finals_txt1.setText("Finals");

        winners_panel1.setBackground(new java.awt.Color(51, 0, 0));
        winners_panel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        winner1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        winner1.setForeground(new java.awt.Color(255, 204, 0));
        winner1.setText(" ");

        javax.swing.GroupLayout winners_panel1Layout = new javax.swing.GroupLayout(winners_panel1);
        winners_panel1.setLayout(winners_panel1Layout);
        winners_panel1Layout.setHorizontalGroup(
            winners_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(winner1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        winners_panel1Layout.setVerticalGroup(
            winners_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(winners_panel1Layout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addComponent(winner1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        winner_txt1.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        winner_txt1.setForeground(new java.awt.Color(255, 255, 102));
        winner_txt1.setText("Winner");

        javax.swing.GroupLayout knockoutTournament_panel1Layout = new javax.swing.GroupLayout(knockoutTournament_panel1);
        knockoutTournament_panel1.setLayout(knockoutTournament_panel1Layout);
        knockoutTournament_panel1Layout.setHorizontalGroup(
            knockoutTournament_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(knockoutTournament_panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(knockoutTournament_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(knockoutTournament_panel1Layout.createSequentialGroup()
                        .addComponent(roundOf32_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(roundOf16_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(knockoutTournament_panel1Layout.createSequentialGroup()
                        .addComponent(roundOf32_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(roundOd16_txt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(knockoutTournament_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(knockoutTournament_panel1Layout.createSequentialGroup()
                        .addComponent(quarterFinals_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(semiFinals_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(knockoutTournament_panel1Layout.createSequentialGroup()
                        .addComponent(quaterFinals_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(semiFinals_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(knockoutTournament_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(knockoutTournament_panel1Layout.createSequentialGroup()
                        .addComponent(finals_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(winners_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(knockoutTournament_panel1Layout.createSequentialGroup()
                        .addComponent(finals_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(winner_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        knockoutTournament_panel1Layout.setVerticalGroup(
            knockoutTournament_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, knockoutTournament_panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(knockoutTournament_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roundOf32_txt1)
                    .addComponent(roundOd16_txt1)
                    .addComponent(quaterFinals_txt1)
                    .addComponent(semiFinals_txt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(finals_txt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(winner_txt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(knockoutTournament_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(roundOf32_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roundOf16_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quarterFinals_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(semiFinals_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(finals_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(winners_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 716, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(knockoutTournament_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 721, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(knockoutTournament_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KnockoutBracket0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KnockoutBracket0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KnockoutBracket0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KnockoutBracket0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KnockoutBracket0().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel R1participant32;
    private javax.swing.JLabel R1participant33;
    private javax.swing.JLabel R1participant34;
    private javax.swing.JLabel R1participant35;
    private javax.swing.JLabel R1participant36;
    private javax.swing.JLabel R1participant37;
    private javax.swing.JLabel R1participant38;
    private javax.swing.JLabel R1participant39;
    private javax.swing.JLabel R1participant40;
    private javax.swing.JLabel R1participant41;
    private javax.swing.JLabel R1participant42;
    private javax.swing.JLabel R1participant43;
    private javax.swing.JLabel R1participant44;
    private javax.swing.JLabel R1participant45;
    private javax.swing.JLabel R1participant46;
    private javax.swing.JLabel R1participant47;
    private javax.swing.JLabel R1participant48;
    private javax.swing.JLabel R1participant49;
    private javax.swing.JLabel R1participant50;
    private javax.swing.JLabel R1participant51;
    private javax.swing.JLabel R1participant52;
    private javax.swing.JLabel R1participant53;
    private javax.swing.JLabel R1participant54;
    private javax.swing.JLabel R1participant55;
    private javax.swing.JLabel R1participant56;
    private javax.swing.JLabel R1participant57;
    private javax.swing.JLabel R1participant58;
    private javax.swing.JLabel R1participant59;
    private javax.swing.JLabel R1participant60;
    private javax.swing.JLabel R1participant61;
    private javax.swing.JLabel R1participant62;
    private javax.swing.JLabel R1participant63;
    private javax.swing.JLabel R1points32;
    private javax.swing.JLabel R1points33;
    private javax.swing.JLabel R1points34;
    private javax.swing.JLabel R1points35;
    private javax.swing.JLabel R1points36;
    private javax.swing.JLabel R1points37;
    private javax.swing.JLabel R1points38;
    private javax.swing.JLabel R1points39;
    private javax.swing.JLabel R1points40;
    private javax.swing.JLabel R1points41;
    private javax.swing.JLabel R1points42;
    private javax.swing.JLabel R1points43;
    private javax.swing.JLabel R1points44;
    private javax.swing.JLabel R1points45;
    private javax.swing.JLabel R1points46;
    private javax.swing.JLabel R1points47;
    private javax.swing.JLabel R1points48;
    private javax.swing.JLabel R1points49;
    private javax.swing.JLabel R1points50;
    private javax.swing.JLabel R1points51;
    private javax.swing.JLabel R1points52;
    private javax.swing.JLabel R1points53;
    private javax.swing.JLabel R1points54;
    private javax.swing.JLabel R1points55;
    private javax.swing.JLabel R1points56;
    private javax.swing.JLabel R1points57;
    private javax.swing.JLabel R1points58;
    private javax.swing.JLabel R1points59;
    private javax.swing.JLabel R1points60;
    private javax.swing.JLabel R1points61;
    private javax.swing.JLabel R1points62;
    private javax.swing.JLabel R1points63;
    private javax.swing.JLabel R2participant16;
    private javax.swing.JLabel R2participant17;
    private javax.swing.JLabel R2participant18;
    private javax.swing.JLabel R2participant19;
    private javax.swing.JLabel R2participant20;
    private javax.swing.JLabel R2participant21;
    private javax.swing.JLabel R2participant22;
    private javax.swing.JLabel R2participant23;
    private javax.swing.JLabel R2participant24;
    private javax.swing.JLabel R2participant25;
    private javax.swing.JLabel R2participant26;
    private javax.swing.JLabel R2participant27;
    private javax.swing.JLabel R2participant28;
    private javax.swing.JLabel R2participant29;
    private javax.swing.JLabel R2participant30;
    private javax.swing.JLabel R2participant31;
    private javax.swing.JLabel R2points16;
    private javax.swing.JLabel R2points17;
    private javax.swing.JLabel R2points18;
    private javax.swing.JLabel R2points19;
    private javax.swing.JLabel R2points20;
    private javax.swing.JLabel R2points21;
    private javax.swing.JLabel R2points22;
    private javax.swing.JLabel R2points23;
    private javax.swing.JLabel R2points24;
    private javax.swing.JLabel R2points25;
    private javax.swing.JLabel R2points26;
    private javax.swing.JLabel R2points27;
    private javax.swing.JLabel R2points28;
    private javax.swing.JLabel R2points29;
    private javax.swing.JLabel R2points30;
    private javax.swing.JLabel R2points31;
    private javax.swing.JLabel R3participant10;
    private javax.swing.JLabel R3participant11;
    private javax.swing.JLabel R3participant12;
    private javax.swing.JLabel R3participant13;
    private javax.swing.JLabel R3participant14;
    private javax.swing.JLabel R3participant15;
    private javax.swing.JLabel R3participant8;
    private javax.swing.JLabel R3participant9;
    private javax.swing.JLabel R3points10;
    private javax.swing.JLabel R3points11;
    private javax.swing.JLabel R3points12;
    private javax.swing.JLabel R3points13;
    private javax.swing.JLabel R3points14;
    private javax.swing.JLabel R3points15;
    private javax.swing.JLabel R3points8;
    private javax.swing.JLabel R3points9;
    private javax.swing.JLabel R4participant4;
    private javax.swing.JLabel R4participant5;
    private javax.swing.JLabel R4participant6;
    private javax.swing.JLabel R4participant7;
    private javax.swing.JLabel R4points4;
    private javax.swing.JLabel R4points5;
    private javax.swing.JLabel R4points6;
    private javax.swing.JLabel R4points7;
    private javax.swing.JLabel R5participant2;
    private javax.swing.JLabel R5participant3;
    private javax.swing.JLabel R5points2;
    private javax.swing.JLabel R5points3;
    private javax.swing.JPanel finals_panel1;
    private javax.swing.JLabel finals_txt1;
    private javax.swing.JPanel knockoutTournament_panel1;
    private javax.swing.JPanel quarterFinals_panel1;
    private javax.swing.JLabel quaterFinals_txt1;
    private javax.swing.JLabel roundOd16_txt1;
    private javax.swing.JPanel roundOf16_panel1;
    private javax.swing.JPanel roundOf32_panel1;
    private javax.swing.JLabel roundOf32_txt1;
    private javax.swing.JPanel semiFinals_panel1;
    private javax.swing.JLabel semiFinals_txt1;
    private javax.swing.JLabel winner1;
    private javax.swing.JLabel winner_txt1;
    private javax.swing.JPanel winners_panel1;
    // End of variables declaration//GEN-END:variables
}
